Iter5
Alexandrfield/Metrics pull request #5
Opened 2024-12-03 08:45 UTC by Alexandrfield

2024-12-04 16:38 UTC, s-shpak commented on cmd/agent/flag.go
> +var globalPollIntervalSecond int
Не используй глобальные переменные. Ты можешь создавать объект, наполнять его и передавать туда, где он будет использоваться

2024-12-04 16:38 UTC, s-shpak commented on cmd/agent/flag.go
> +	if envServerAdderess := os.Getenv("ADDRESS"); envServerAdderess != "" {
Вместо `Getenv` лучше использовать `LookupEnv` (https://pkg.go.dev/os#LookupEnv) для того чтобы отличать пустую переменную окружения от необъявленной

2024-12-04 16:39 UTC, s-shpak commented on cmd/agent/flag.go
Постарайся оставлять в `main.go` (и в пакете `main`) как можно меньше логики: там могут лежать только создание и настройка компонентов и запуск сервиса. Всю остальную логику нужно перенести в `internal`.

2024-12-04 16:40 UTC, s-shpak commented on cmd/agent/main.go
> +		fmt.Printf("http.NewRequest. err: %s\n", err)
Посмотри вебинар и обсуждение того, как надо обрабатывать ошибки.

Ошибка прокидывается максимально наверх и обрабатывается на том слое, где это возможно. Кроме того, если здесь произошла ошибка, ты не можешь продолжить выполнение программы.

2024-12-04 16:41 UTC, s-shpak commented on cmd/agent/main.go
> +			go reportMetrics(client, metricsReport)
Не стоит запускать новую горутину для отправки метрик: это чревато тем, что количество запущенных горутин будет постоянно расти (если отправка метрик будет занимать больше, чем `ReportInterval`) . Делай это синхронно

2024-12-04 16:42 UTC, s-shpak commented on cmd/agent/main.go
> +			updateCounterMetrics(metricsCounter)
Сейчас это работает некорректно: счетчик увеличивается при каждом сборе метрика на 1, а сервер прибалвяет полученное значение к пердыдущему. Вот пример того, что может произойти:

- агент собрал метрики 3 раза и отправляет серверу это значение
- сервер сохраняет его
- агент собрал метрики еще 2 раза и отправляет серверу значение 5 (3 + 2)
- сервер прибавляет его к предыдущему. С т.з. сервера агент произвел 8 сборов метрик

Подумай, как это исправить

2024-12-04 16:43 UTC, s-shpak commented on cmd/server/main.go
> +	fmt.Printf("defaultAnswer. req:%v;\n", req)
Не используй пакет `fmt` для логгирования, вместо него используй `log`. В дальнейшем мы перейдем либо на `slog`, либо на сторонний линтер типа `zap`.

2024-12-04 16:43 UTC, s-shpak commented on cmd/server/main.go
> +<html>
Для работы с `HTML` документами лучше использовать пакет html/template: https://pkg.go.dev/html/template

2024-12-04 16:44 UTC, s-shpak commented on cmd/server/main.go
> +		panic(err)
Паниковать не надо: используй `log.Fatal` для:
    1. вывода ошибки
    2. завершения процесса с ошибкой

2024-12-04 16:44 UTC, s-shpak commented on go.mod
> +
Можно перейти на `go 1.22`

2024-12-04 16:44 UTC, s-shpak commented on internal/requestHandler/requestHandler.go
> +var globalMemStorage storage.MemStorageI = nil
Глобальные переменные не нужны

2024-12-04 16:45 UTC, s-shpak commented on internal/storage/storage.go
> +type MemStorageI interface {
В Go интерфейсы принято объявлять рядом с местом их использования: в одном пакете и, чаще всего, рядом с функцией/методом, которые их используют. Существуют исключения, но это не тот случай

Кроме того в Go не принято добавлять префикс (или суффикс) I для обозначения интерфейса

2024-12-04 16:45 UTC, s-shpak commented on internal/storage/storage.go
> +		return false
В подобных случаях возвращай ошибки и проверяй их выше

2024-12-09 14:27 UTC, Alexandrfield commented on cmd/agent/flag.go
> +	if envServerAdderess := os.Getenv("ADDRESS"); envServerAdderess != "" {
Исправил. Но в этом случаеБ теперь я проверяю только на тоБ существует ли перменная в переменных окружения и не проверяю само значение на пустоту (иначе прошлый вариант был бы проще)

2024-12-09 14:29 UTC, Alexandrfield commented on cmd/agent/main.go
> +			go reportMetrics(client, metricsReport)
Исправил. Но в таком случае, при медленном соединении, время проверки метрик на платформе тоже изменяется и дынные будут собираться не в тот интервалБ который мы указываем в параметрах

2024-12-09 23:23 UTC, s-shpak commented on cmd/agent/flag.go
> +	if envServerAdderess := os.Getenv("ADDRESS"); envServerAdderess != "" {
Если ты хочешь делать валидацию значений, то я бы делал сначала получение конфигурации, а потом проверку значений.

2024-12-09 23:23 UTC, s-shpak commented on cmd/agent/flag.go
Разбор флагов и т.п. тоже можно положить в `internal`

2024-12-09 23:26 UTC, s-shpak commented on cmd/agent/main.go
> +			go reportMetrics(client, metricsReport)
Это поправится на четвертом спринте, пока ничего страшного

2024-12-09 23:31 UTC, s-shpak requested changes

2024-12-09 23:31 UTC, s-shpak commented on internal/agent/metrics.go
> +		metricsCounter[key] = 0
Каунтер может сброситься, но метрики не уйдут на сервер из-за ошибки: в этом случае величина на сервере опять будет рассчитана некорректно. Исправь это, пожалуйста

2024-12-09 23:31 UTC, s-shpak commented on internal/agent/metrics.go
> +		log.Printf("http.NewRequest.Do err: %s\n", err)
А почеиу эту ошибку не вернуть наверх ?

2024-12-09 23:31 UTC, s-shpak commented on internal/agent/metrics.go
> +		log.Printf("Error reading body. err%s\n ", err)
После этого продолжать это выполнение функции нельзя

2024-12-09 23:31 UTC, s-shpak commented on internal/storage/storage.go
> +var ErrCantParseDataIssue = errors.New("can't parser or use data")
Ошибки стоит объявлять в виде глобальных эксопртируемых переменных только тогда, когда они являются частью интерфейса, предоставляемого пакетом: т.е. другой пакет, который его использует будет иметь информацию о том, что какая-то функция может вернуть эти экспортируемую ошибку.

В данном случае это не так: эта ошибка нигде больше не используется -- другие пакеты не используют ее при вызове функций `errors.Is`/`errors.As`. пПотому нет смысла объявлять ее в качестве глобальной переменной.

2024-12-09 23:31 UTC, s-shpak commented on internal/storage/storage_test.go
> +			log.Printf("Error for test; err:%v\n", err)
1. Если это тест, то здесь надо отметить его как проваленный через `t.Error()`

2. Вызов `t.Error()` не завершает выполнение тест-кейса, хотя смылса продолжать его, как правило, нет, т.к. после первой ошибки тест обычно более не в валдином состоянии и большинство (если не все) следующие проверки заврешатся с ошибкой. найти при жтиом корневую проблему станет сложнее.

Я бы советовал вызывать `return` после `t.Error()`, чтобы явным образом завершить выполнение тест-кейса.

2024-12-10 06:48 UTC, Alexandrfield commented on internal/agent/metrics.go
> +		metricsCounter[key] = 0
Спасибо. Сейчас сообразил, что проблема будет всегда, если не учитывать ответ сервера

2024-12-10 12:52 UTC, s-shpak approved these changes

2024-12-22 12:16 UTC, merged