Iter9
Alexandrfield/Metrics pull request #9
Opened 2024-12-30 12:47 UTC by Alexandrfield

2025-01-02 20:57 UTC, s-shpak requested changes

2025-01-02 20:57 UTC, s-shpak commented on cmd/server/main.go
> +			fmt.Printf("Rcovert. Panic occurred:\n")
Не используй пакет `fmt` для логгирования, вместо него используй кастомный логгер

2025-01-02 20:57 UTC, s-shpak commented on cmd/server/main.go
> +	logger.Debugf("config file: %v", config)
Конфигурацию лучше не логировать: в объекте конфигурации почти всегда будут пароли, ключи и т.п., что попадать в логи не должно.

Если тебе почему-то нужно логировать конфигурацию, то есть два варианта:
1. логировать только те поля, которые нужны
2. написать метод преобразования объекта конфигурации в строковое представление, где некоторые поля не будут видны (это можно сделать при помощи https://pkg.go.dev/encoding/json#example-package-CustomMarshalJSON, например)

2025-01-02 20:57 UTC, s-shpak commented on cmd/server/main.go
> +	// router.Post(`/update/`, server.WithLogging(logger, servHandler.DefaultAnswer))
dead code ?

2025-01-02 20:57 UTC, s-shpak commented on cmd/server/main.go
> +		close(done)
Это лучше поместить в defer в начале функции

2025-01-02 20:57 UTC, s-shpak commented on cmd/server/main.go
> +			logger.Fatal("Unexpected error. err:%s", err)
Если ты делаешь graceful shutdown, то это не имеет смысла: log.Fatal должен выполняться только в "корневой горутине", иначе одна из горутин может завершить весь процесс, не дожидаясь окончания работы других горутин

2025-01-02 20:57 UTC, s-shpak commented on internal/agent/metrics.go
> +	logger common.Loger) (int, error) {
```suggestion
	logger common.Loger,
) (int, error) {
```

2025-01-02 20:57 UTC, s-shpak commented on internal/agent/metrics.go
> +		return http.StatusBadRequest, fmt.Errorf("problem with marshal JSON file. err:%w", err)
Мне не очень нравится, что функция возвращает статус-код: запрос на сервер еще не ушел, зачем возвращать какой-либо статус-код. Я бы возвращал ошибку конкретного типа и обрабатывал бы ее выше

2025-01-02 20:57 UTC, s-shpak commented on internal/requestHandler/requestHandler.go
> +		rep.logger.Debugf("internal error:%w", err)
А почему на уровне дебагинга? И, опять же, зачем возвращать здесь статус-код, когда можно вернуть ошибку конкретного типа, чтобы выше решить какой статус-код отдать клиенту ?

2025-01-02 20:57 UTC, s-shpak commented on internal/requestHandler/requestHandler.go
В го принято использовать либо snake-case, либо kebab-case в именах файлов.

Проще всегод назвать так: `internal/handlers/request/request.go`

2025-01-02 20:57 UTC, s-shpak commented on internal/server/flag.go
> +			fmt.Printf("error atoi STORE_INTERVAL; err: %s\n", err)
1. Логировать надо при помощи логгера
2. Fallback на дефолтные значения чаще стреляет в ногу, чем помогает. Представь себе, что ты запускаешь сервис с некорректной конфигурацией, и он сразу падает. Ты правишь конфигурацию, далее сервис работает корректно.

Теперь представь, что ты запускаешь сервис, и он запускается, но при инициализации компонентов происходит fallback на дефолтное значение, потому что заданное тобой некорректно. Тогда ты будешь думать, что сервис проиницализирован одним образом, а он будет работать по-другому и неожиданно для тебя.

https://stackoverflow.com/questions/2807241/what-does-the-expression-fail-early-mean-and-when-would-you-want-to-do-so

2025-01-02 20:57 UTC, s-shpak commented on internal/server/server.go
> +		// lw := loggingResponseWriter{
deadcode

2025-01-02 20:57 UTC, s-shpak commented on internal/storage/storage.go
> +	// if st.Config.StoreIntervalSecond == 0 {
deadcode

2025-01-02 20:57 UTC, s-shpak commented on internal/storage/storage.go
> +	// if st.Config.StoreIntervalSecond == 0 {
deadcode

2025-01-03 14:59 UTC, Alexandrfield commented on internal/requestHandler/requestHandler.go
> +		rep.logger.Debugf("internal error:%w", err)
исправил на работу через ошибку

2025-01-03 15:00 UTC, Alexandrfield commented on cmd/server/main.go
> +	// router.Post(`/update/`, server.WithLogging(logger, servHandler.DefaultAnswer))
удалил

2025-01-03 15:01 UTC, Alexandrfield commented on internal/agent/metrics.go
> +	logger common.Loger) (int, error) {
исправил

2025-01-06 08:49 UTC, s-shpak approved these changes

2025-01-08 11:07 UTC, merged